import { Question } from '../types/quiz';

export const FALLBACK_QUESTIONS: Question[] = [
  // Sciences & Nature (10)
  {
    id: 1,
    question: "Quelle est la formule chimique de l'eau ?",
    options: ['H2O', 'CO2', 'NaCl', 'O2'],
    correct_index: 0,
    explanation: "L'eau est composée de 2 atomes d'hydrogène et 1 atome d'oxygène.",
    category: 'science',
  },
  {
    id: 2,
    question: 'Quel organe produit l\'insuline ?',
    options: ['Le foie', 'Le pancréas', 'Les reins', 'L\'estomac'],
    correct_index: 1,
    explanation: 'Le pancréas produit l\'insuline qui régule le taux de sucre dans le sang.',
    category: 'science',
  },
  {
    id: 3,
    question: 'Combien de chromosomes possède l\'être humain ?',
    options: ['23', '46', '48', '44'],
    correct_index: 1,
    explanation: 'L\'humain possède 46 chromosomes, soit 23 paires.',
    category: 'science',
  },
  {
    id: 4,
    question: 'Quelle planète est la plus grande du système solaire ?',
    options: ['Saturne', 'Neptune', 'Jupiter', 'Uranus'],
    correct_index: 2,
    explanation: 'Jupiter est la plus grande planète, avec un diamètre de 142 984 km.',
    category: 'science',
  },
  {
    id: 5,
    question: 'À quelle vitesse se propage la lumière dans le vide ?',
    options: ['300 000 km/s', '150 000 km/s', '500 000 km/s', '200 000 km/s'],
    correct_index: 0,
    explanation: 'La lumière se propage à environ 299 792 km/s dans le vide.',
    category: 'science',
  },
  {
    id: 6,
    question: 'Quel est le symbole chimique de l\'or ?',
    options: ['Or', 'Go', 'Au', 'Ag'],
    correct_index: 2,
    explanation: 'L\'or a pour symbole Au, du latin "aurum".',
    category: 'science',
  },
  {
    id: 7,
    question: 'Combien d\'os y a-t-il dans le corps humain adulte ?',
    options: ['206', '250', '180', '312'],
    correct_index: 0,
    explanation: 'Le squelette adulte compte 206 os.',
    category: 'science',
  },
  {
    id: 8,
    question: 'Quelle est la température d\'ébullition de l\'eau au niveau de la mer ?',
    options: ['90°C', '95°C', '100°C', '105°C'],
    correct_index: 2,
    explanation: 'L\'eau bout à 100°C à une pression atmosphérique normale.',
    category: 'science',
  },
  {
    id: 9,
    question: 'Qui a découvert la pénicilline ?',
    options: ['Louis Pasteur', 'Alexander Fleming', 'Marie Curie', 'Robert Koch'],
    correct_index: 1,
    explanation: 'Alexander Fleming a découvert la pénicilline en 1928.',
    category: 'science',
  },
  {
    id: 10,
    question: 'Quel est le gaz le plus abondant dans l\'atmosphère terrestre ?',
    options: ['Oxygène', 'Dioxyde de carbone', 'Argon', 'Azote'],
    correct_index: 3,
    explanation: 'L\'azote représente environ 78% de l\'atmosphère.',
    category: 'science',
  },

  // Histoire & Géographie Afrique (10)
  {
    id: 11,
    question: 'Quelle est la capitale du Sénégal ?',
    options: ['Abidjan', 'Dakar', 'Bamako', 'Conakry'],
    correct_index: 1,
    explanation: 'Dakar est la capitale et la plus grande ville du Sénégal.',
    category: 'history',
  },
  {
    id: 12,
    question: 'Quel fleuve est le plus long d\'Afrique ?',
    options: ['Congo', 'Niger', 'Nil', 'Zambèze'],
    correct_index: 2,
    explanation: 'Le Nil est le plus long fleuve d\'Afrique avec 6 650 km.',
    category: 'history',
  },
  {
    id: 13,
    question: 'En quelle année le Sénégal a-t-il obtenu son indépendance ?',
    options: ['1958', '1960', '1962', '1965'],
    correct_index: 1,
    explanation: 'Le Sénégal a proclamé son indépendance le 4 avril 1960.',
    category: 'history',
  },
  {
    id: 14,
    question: 'Quelle est la monnaie utilisée en Côte d\'Ivoire ?',
    options: ['Franc ivoirien', 'Cedi', 'FCFA', 'Naira'],
    correct_index: 2,
    explanation: 'La Côte d\'Ivoire utilise le Franc CFA de l\'Afrique de l\'Ouest.',
    category: 'history',
  },
  {
    id: 15,
    question: 'Qui était le premier président du Ghana indépendant ?',
    options: ['Kofi Annan', 'Kwame Nkrumah', 'Jerry Rawlings', 'John Mahama'],
    correct_index: 1,
    explanation: 'Kwame Nkrumah fut le premier président du Ghana en 1960.',
    category: 'history',
  },
  {
    id: 16,
    question: 'Quel est le pays le plus peuplé d\'Afrique ?',
    options: ['Éthiopie', 'RD Congo', 'Égypte', 'Nigeria'],
    correct_index: 3,
    explanation: 'Le Nigeria est le pays le plus peuplé d\'Afrique avec plus de 200 millions d\'habitants.',
    category: 'history',
  },
  {
    id: 17,
    question: 'Quelle montagne est la plus haute d\'Afrique ?',
    options: ['Mont Kenya', 'Kilimandjaro', 'Mont Cameroun', 'Ras Dashen'],
    correct_index: 1,
    explanation: 'Le Kilimandjaro en Tanzanie culmine à 5 895 mètres.',
    category: 'history',
  },
  {
    id: 18,
    question: 'De quel pays la ville de Tombouctou fait-elle partie ?',
    options: ['Sénégal', 'Burkina Faso', 'Niger', 'Mali'],
    correct_index: 3,
    explanation: 'Tombouctou est une ville historique du Mali, ancienne cité du savoir.',
    category: 'history',
  },
  {
    id: 19,
    question: 'Quelle est la capitale de l\'Éthiopie ?',
    options: ['Nairobi', 'Kampala', 'Addis-Abeba', 'Khartoum'],
    correct_index: 2,
    explanation: 'Addis-Abeba est la capitale de l\'Éthiopie et siège de l\'Union Africaine.',
    category: 'history',
  },
  {
    id: 20,
    question: 'Quel empire africain contrôlait les mines d\'or du Bambuk au Moyen Âge ?',
    options: ['Empire du Mali', 'Empire Songhaï', 'Empire du Ghana', 'Royaume du Bénin'],
    correct_index: 2,
    explanation: 'L\'Empire du Ghana contrôlait le commerce de l\'or entre le VIIIe et le XIe siècle.',
    category: 'history',
  },

  // Technologie (10)
  {
    id: 21,
    question: 'Quelle entreprise a créé le système d\'exploitation Android ?',
    options: ['Apple', 'Microsoft', 'Google', 'Samsung'],
    correct_index: 2,
    explanation: 'Android a été développé par Google, acquis en 2005.',
    category: 'technology',
  },
  {
    id: 22,
    question: 'Que signifie l\'acronyme "HTTP" ?',
    options: [
      'HyperText Transfer Protocol',
      'High Tech Transfer Process',
      'Hyperlink Text Transport Protocol',
      'HyperText Transmission Process',
    ],
    correct_index: 0,
    explanation: 'HTTP signifie HyperText Transfer Protocol, protocole de communication web.',
    category: 'technology',
  },
  {
    id: 23,
    question: 'En quelle année le premier iPhone a-t-il été lancé ?',
    options: ['2005', '2006', '2007', '2008'],
    correct_index: 2,
    explanation: 'Steve Jobs a présenté le premier iPhone le 9 janvier 2007.',
    category: 'technology',
  },
  {
    id: 24,
    question: 'Quel langage de programmation est principalement utilisé pour le développement iOS ?',
    options: ['Java', 'Kotlin', 'Swift', 'C#'],
    correct_index: 2,
    explanation: 'Swift est le langage principal d\'Apple pour le développement iOS depuis 2014.',
    category: 'technology',
  },
  {
    id: 25,
    question: 'Qu\'est-ce qu\'un CPU ?',
    options: [
      'Central Processing Unit',
      'Computer Power Unit',
      'Central Power Unit',
      'Computing Process Utility',
    ],
    correct_index: 0,
    explanation: 'CPU signifie Central Processing Unit, le processeur central d\'un ordinateur.',
    category: 'technology',
  },
  {
    id: 26,
    question: 'Combien de bits composent un octet ?',
    options: ['4', '8', '16', '32'],
    correct_index: 1,
    explanation: 'Un octet est composé de 8 bits.',
    category: 'technology',
  },
  {
    id: 27,
    question: 'Quel protocole est utilisé pour envoyer des emails ?',
    options: ['FTP', 'HTTP', 'SMTP', 'SSH'],
    correct_index: 2,
    explanation: 'SMTP (Simple Mail Transfer Protocol) est le protocole standard d\'envoi d\'emails.',
    category: 'technology',
  },
  {
    id: 28,
    question: 'Qui a fondé Tesla ?',
    options: [
      'Elon Musk seul',
      'Martin Eberhard et Marc Tarpenning',
      'Jeff Bezos',
      'Bill Gates',
    ],
    correct_index: 1,
    explanation: 'Tesla a été fondée en 2003 par Martin Eberhard et Marc Tarpenning.',
    category: 'technology',
  },
  {
    id: 29,
    question: 'Que représente le "G" dans "5G" ?',
    options: ['Gigabit', 'Global', 'Génération', 'Giga'],
    correct_index: 2,
    explanation: 'Le "G" signifie "Génération". La 5G est la 5e génération de réseau mobile.',
    category: 'technology',
  },
  {
    id: 30,
    question: 'Quel langage de programmation a été créé par Guido van Rossum ?',
    options: ['Java', 'Ruby', 'Python', 'Perl'],
    correct_index: 2,
    explanation: 'Python a été créé par Guido van Rossum et publié en 1991.',
    category: 'technology',
  },

  // Culture Générale (10)
  {
    id: 31,
    question: 'Quelle est la langue la plus parlée dans le monde ?',
    options: ['Anglais', 'Espagnol', 'Mandarin', 'Hindi'],
    correct_index: 2,
    explanation: 'Le mandarin est la langue maternelle la plus parlée avec plus d\'1 milliard de locuteurs.',
    category: 'culture',
  },
  {
    id: 32,
    question: 'Combien de continents y a-t-il sur Terre ?',
    options: ['5', '6', '7', '8'],
    correct_index: 2,
    explanation: 'Il y a 7 continents : Afrique, Amérique du Nord, Amérique du Sud, Antarctique, Asie, Europe, Océanie.',
    category: 'culture',
  },
  {
    id: 33,
    question: 'Qui a peint la Joconde ?',
    options: ['Michel-Ange', 'Raphael', 'Léonard de Vinci', 'Botticelli'],
    correct_index: 2,
    explanation: 'La Joconde a été peinte par Léonard de Vinci entre 1503 et 1519.',
    category: 'culture',
  },
  {
    id: 34,
    question: 'Quel est le pays le plus grand du monde en superficie ?',
    options: ['Canada', 'Chine', 'États-Unis', 'Russie'],
    correct_index: 3,
    explanation: 'La Russie est le plus grand pays du monde avec 17,1 millions de km².',
    category: 'culture',
  },
  {
    id: 35,
    question: 'En quelle année a eu lieu la Révolution française ?',
    options: ['1776', '1789', '1799', '1815'],
    correct_index: 1,
    explanation: 'La Révolution française a débuté en 1789 avec la prise de la Bastille.',
    category: 'culture',
  },
  {
    id: 36,
    question: 'Quelle est la monnaie du Japon ?',
    options: ['Yuan', 'Won', 'Yen', 'Ringgit'],
    correct_index: 2,
    explanation: 'Le Yen (¥) est la monnaie officielle du Japon.',
    category: 'culture',
  },
  {
    id: 37,
    question: 'Quel auteur a écrit "Les Misérables" ?',
    options: ['Émile Zola', 'Victor Hugo', 'Gustave Flaubert', 'Alexandre Dumas'],
    correct_index: 1,
    explanation: 'Les Misérables a été écrit par Victor Hugo et publié en 1862.',
    category: 'culture',
  },
  {
    id: 38,
    question: 'Combien de joueurs composent une équipe de football sur le terrain ?',
    options: ['9', '10', '11', '12'],
    correct_index: 2,
    explanation: 'Chaque équipe de football joue avec 11 joueurs sur le terrain.',
    category: 'culture',
  },
  {
    id: 39,
    question: 'Quelle est la capitale de l\'Australie ?',
    options: ['Sydney', 'Melbourne', 'Brisbane', 'Canberra'],
    correct_index: 3,
    explanation: 'Canberra est la capitale de l\'Australie, choisie comme compromis entre Sydney et Melbourne.',
    category: 'culture',
  },
  {
    id: 40,
    question: 'Quel philosophe a dit "Je pense donc je suis" ?',
    options: ['Platon', 'Aristote', 'René Descartes', 'Emmanuel Kant'],
    correct_index: 2,
    explanation: 'René Descartes a formulé le "Cogito ergo sum" dans ses Méditations de 1641.',
    category: 'culture',
  },

  // Sport (10)
  {
    id: 41,
    question: 'Quel pays a remporté la Coupe du Monde 2022 ?',
    options: ['France', 'Brésil', 'Argentine', 'Allemagne'],
    correct_index: 2,
    explanation: 'L\'Argentine a battu la France en finale de la Coupe du Monde 2022 au Qatar.',
    category: 'sport',
  },
  {
    id: 42,
    question: 'Combien de sets faut-il gagner pour remporter un match de tennis en Grand Chelem masculin ?',
    options: ['2', '3', '4', '5'],
    correct_index: 1,
    explanation: 'En Grand Chelem masculin, il faut gagner 3 sets (meilleur des 5).',
    category: 'sport',
  },
  {
    id: 43,
    question: 'Dans quel sport utilise-t-on un "smash" ?',
    options: ['Football', 'Rugby', 'Badminton', 'Golf'],
    correct_index: 2,
    explanation: 'Le smash est un coup puissant utilisé au badminton, tennis et volleyball.',
    category: 'sport',
  },
  {
    id: 44,
    question: 'Quel athlète détient le record du monde du 100m masculin ?',
    options: ['Justin Gatlin', 'Tyson Gay', 'Usain Bolt', 'Yohan Blake'],
    correct_index: 2,
    explanation: 'Usain Bolt détient le record du monde avec 9,58 secondes établi en 2009.',
    category: 'sport',
  },
  {
    id: 45,
    question: 'Combien de points vaut un panier à 3 points au basketball ?',
    options: ['1', '2', '3', '4'],
    correct_index: 2,
    explanation: 'Un tir réussi derrière la ligne des 3 points rapporte 3 points.',
    category: 'sport',
  },
  {
    id: 46,
    question: 'Quel club a remporté le plus de Ligues des Champions ?',
    options: ['FC Barcelone', 'Bayern Munich', 'Real Madrid', 'Liverpool'],
    correct_index: 2,
    explanation: 'Le Real Madrid a remporté 15 Ligues des Champions.',
    category: 'sport',
  },
  {
    id: 47,
    question: 'Quelle distance court-on lors d\'un marathon ?',
    options: ['40 km', '42,195 km', '45 km', '50 km'],
    correct_index: 1,
    explanation: 'La distance officielle d\'un marathon est de 42,195 km.',
    category: 'sport',
  },
  {
    id: 48,
    question: 'Dans quel sport pratique-t-on le "coup franc" ?',
    options: ['Rugby', 'Handball', 'Football', 'Basket'],
    correct_index: 2,
    explanation: 'Le coup franc est une reprise de jeu au football après une faute.',
    category: 'sport',
  },
  {
    id: 49,
    question: 'Quel pays a inventé le judo ?',
    options: ['Chine', 'Corée', 'Japon', 'Thaïlande'],
    correct_index: 2,
    explanation: 'Le judo a été créé au Japon par Jigoro Kano en 1882.',
    category: 'sport',
  },
  {
    id: 50,
    question: 'Combien de joueurs composent une équipe de rugby à XV ?',
    options: ['13', '15', '17', '11'],
    correct_index: 1,
    explanation: 'Le rugby à XV se joue avec 15 joueurs par équipe sur le terrain.',
    category: 'sport',
  },
];
